feat(skinned-mesh): add support for 'Child Of' constraint on bones
StjerneIdioten/I3D-Blender-Addon pull request #224
Opened 2024-12-07 00:46 UTC by NMC-TBone

Make it possible for bones in armatures to set a custom parent
based on the 'Child Of' constraint target (PoseBone). Simplifies
the workflow by allowing a single armature to manage
all bones, instead of requiring one armature per bone.

Note: With current implementation the armature need to be added outside the hierarchy at the bottom of everything you want to export

2024-12-07 15:21 UTC, NMC-TBone commented
Matrix calc should now work as expected, added additional comments and refined the whole conversion function

2025-01-04 02:32 UTC, NMC-TBone commented
Probably need to do some changes to this when #238 is merged.

I am also not 100% sure that the approuch of the "Child Of" constrain implementaion here is the best solution.

2025-01-13 23:54 UTC, StjerneIdioten requested changes
I think a little mistake in one of the files also I cannot' run your examples as you haven't included the mappings file in the .zip, if I remove fix the bug and remove the mappings then I can export. But I don't seem to understand how this is supposed to work as I am not moving anything in neither Blender nor GE except for the skinned mesh. It might just be that I don't understand what "child of" is to be used for (Except definitely not for chains of bones, as per Blender's manual!)

2025-01-13 23:54 UTC, StjerneIdioten commented on addon/i3dio/node_classes/skinned_mesh.py
> +                    self.i3d.deferred_constraints.append((bone_object, target, None))
```suggestion
                    self.i3d.deferred_constraints.append((bone_object, target))
```
This extra `None` makes everything fail, to me it looks like a merge error? Because I cannot see why it should be there.

2025-01-14 16:56 UTC, NMC-TBone commented
> I think a little mistake in one of the files also I cannot' run your examples as you haven't included the mappings file in the .zip, if I remove fix the bug and remove the mappings then I can export. But I don't seem to understand how this is supposed to work as I am not moving anything in neither Blender nor GE except for the skinned mesh. It might just be that I don't understand what "child of" is to be used for (Except definitely not for chains of bones, as per Blender's manual!)

If you first merge #255 this should now work as expected. Also updated the example .zip added collection export to the blend file examples as well

Think most cases that could potentially happen have been handled now

2025-01-14 22:49 UTC, StjerneIdioten approved these changes

2025-01-14 22:50 UTC, merged